# Generated by Django 3.0.1 on 2019-12-25 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.DecimalField(decimal_places=0, max_digits=11)),
                ('gender', models.CharField(max_length=5)),
                ('dept', models.IntegerField()),
                ('roll', models.DecimalField(decimal_places=0, max_digits=7)),
                ('reg', models.DecimalField(decimal_places=0, max_digits=4)),
                ('adm_year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('cur_year', models.IntegerField()),
                ('sems', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
