# Generated by Django 3.0.1 on 2019-12-26 17:48

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20191226_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='picture',
            field=models.ImageField(null=True, upload_to=accounts.models.image_path_student),
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.DecimalField(decimal_places=0, max_digits=11)),
                ('gender', models.CharField(max_length=5)),
                ('dept', models.IntegerField()),
                ('designation', models.IntegerField()),
                ('picture', models.ImageField(null=True, upload_to=accounts.models.image_path_teacher)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
